eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address: localhost
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}