eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address: api-order
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}