spring:
  profiles:
    active: dev
  application:
    name: zuul

server:
  port: 8771

zuul:
  routes:
    user:
      path: /api-user/**
      serviceId: api-user
    order:
      path: /api-order/**
      serviceId: api-order
  sensitive-headers: Cookie,Set-Cookie,Authorization,Uid

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
