spring:
  application:
    name: config-server

  # git管理配置https://github.com/mingwulipo/config-repertory.git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mingwulipo/k8s-cloud-demo.git
          username: mingwulipo
          password: github8278784
          label: main
          #仓库目录
          searchPaths: config-repertory
          #加载到本地目录，把整个git仓库拷贝到本地了，不是只拷贝searchPaths指定的目录
          #basedir: ./config-repo
          force-pull: true

server:
  port: 9050
